"""add picture_url to Cookie

Revision ID: 7d187e3e2f00
Revises: 6750c16bb008
Create Date: 2024-10-11 17:01:06.489538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d187e3e2f00'
down_revision = '6750c16bb008'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cookie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cookie', schema=None) as batch_op:
        batch_op.drop_column('picture_url')

    # ### end Alembic commands ###
