"""create relationship between cookies and orders

Revision ID: a3a0e3e1944a
Revises: 7d37e0fe9807
Create Date: 2024-10-11 20:52:27.461306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3a0e3e1944a'
down_revision = '7d37e0fe9807'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cookie_order',
    sa.Column('cookie_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('number_of_cookies', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cookie_id'], ['cookie.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('cookie_id', 'order_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cookie_order')
    # ### end Alembic commands ###
